-- 044b: cleaned 2026 delivery history (Jan 1 2026 onward) — run AFTER 044
-- 132 rows from the DELIVERIES sheet, company names normalized.

INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-01-10', 'Jeremy Gibson', 7.0, 275, 'Diane Denise', (SELECT id FROM companies WHERE name='Reliant'), 'Nighttime Van Delivery', 'Granite City', 450.0, true, NULL, true, '217-559-5809', 'Bill for two bags of flour $4.81 purchased on business credit card, purchased corn starch from Ruler Foods $3.59. sent MK pic of reciept', 'Jen', NULL, 'Pizza Hut: $26.16');
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-01-11', 'Jeremy Gibson', 2.0, 150, 'R Stewart', (SELECT id FROM companies WHERE name='Kirby'), 'Nighttime Boat Delivery', 'Grafton', 450.0, false, NULL, true, '225-270-1132', 'Picked up a router from Walmart grocery pickup, bought 25'' ethernet cable with my personal card and they venmoed me. No charge for this. ', 'Jen', NULL, 'None');
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-01-11', 'Tanner Critchfield', 2.0, 50.0, 'Prosperity', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Boat Delivery', 'Grafton', 350.0, true, NULL, true, '314-803-4832', 'No issues', 'Jen', NULL, 'None');
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-01-11', 'Brett Lander', 3.0, 175.0, 'Coop Mariner', (SELECT id FROM companies WHERE name='Reliant'), 'Nighttime Boat Delivery', 'Grafton', 450.0, false, NULL, true, '314-803-4815', 'No issues, very large order', 'Jen', NULL, 'None');
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-01-15', 'Nipper DeSherlia', 3.0, 175.0, 'Coop Mariner', (SELECT id FROM companies WHERE name='Reliant'), 'Nighttime Boat Delivery', 'Grafton', 450.0, false, NULL, true, '314-803-4815', 'No issues, gave Nipper one additional hour because he pulled the boat out and parked it by the coolers for us', 'Jen', NULL, 'None');
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-01-15', 'Rhylon DeSherlia', 2.0, 50.0, 'Philip Pfeffer', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'Ingram Depo', 350.0, NULL, NULL, true, '270-933-0908', 'Bill for a 12 pk Barqs $9.14 used Jens personal card by accident, Bill for 12pk Dr Pepper and cigarettes $24.54 used card in van', 'Jen', NULL, 'Chip clip and notebook');
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-01-15', 'Keith Kasinger', 3.5, 87.5, 'Ardyce Randall', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Van Delivery', 'Artco Terminal', 450.0, true, NULL, true, '314-803-4812', 'Purchased a case of red bull for the captain with my personal card, and he venmoed me. This is the delivery I picked up from Sinclairs and brought to Grafton.', 'Jen', NULL, 'Chip clip and notebook');
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-01-16', 'Nipper DeSherlia', 2.0, 50.0, NULL, NULL, 'Pick up items Keith Kessigner left on Ardyce Randall by accident. ', NULL, NULL, NULL, NULL, true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-01-20', 'Travis Maurer', 4.0, 200, 'Prosperity', (SELECT id FROM companies WHERE name='Artco'), 'Nighttime Boat Delivery', 'Artco Terminal', 450.0, true, NULL, true, '314-803-4832', 'None', 'Jen', NULL, 'Chip clip and notebook');
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-01-20', 'Travis Maurer', 4.5, 162.5, 'New Dawn', (SELECT id FROM companies WHERE name='Artco'), 'Nighttime Boat Delivery', 'Artco Terminal', 450.0, true, NULL, true, '314-803-4830', 'None', 'Jen', NULL, 'Chip clip and notebook');
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-01-20', 'Nipper DeSherlia', 0.0, 50.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, NULL, 'Helped Travis get gas at the properity. Travis asked that $50 of his pay go to Nipper. ', 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-01-30', 'Ira Moore', 4.0, 100.0, 'Thomas K', (SELECT id FROM companies WHERE name='Reliant'), 'Daytime Van Delivery', 'Ingram', 450.0, false, NULL, true, '662-394-1563', 'Trained and Did delivery', 'Laura', NULL, 'Cup and chip clip');
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-01-31', 'Ira Moore', 6.0, 150.0, 'Diane Denise', (SELECT id FROM companies WHERE name='Reliant'), 'Daytime Van Delivery Extended', 'Granite City then PTL', 450.0, false, NULL, true, '270-559-5809', 'Had issue with ice and needed to switch to PTL once we got there', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-02-07', 'Travis Maurer', 4.5, 212.5, 'Dwaine Stephens', (SELECT id FROM companies WHERE name='Excel Marine'), 'Nighttime Van Delivery Extended', 'Gateway Arch', 550.0, false, NULL, true, '270-556-5388', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-02-08', 'Travis Maurer', 3.0, 75.0, 'Susan K', (SELECT id FROM companies WHERE name='Reliant'), 'Daytime Van Delivery', 'Ingram', 450.0, false, NULL, true, '662-394-1562', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-02-08', 'Ira Moore', 3.0, 75.0, 'Ardyce Randyl', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Van Delivery', 'Artco Terminal', 450.0, false, NULL, true, '314-802-4812', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-02-17', 'Rhylon DeSherlia', 6.0, 150.0, 'Susan Stall', (SELECT id FROM companies WHERE name='Canal'), 'Daytime Van Delivery Extended', 'Dock Past Beardstown', 500.0, true, NULL, true, '901-833-0185', 'This is our first delivery with them.  They sent email with invoice information.', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-02-18', 'Nipper DeSherlia', 2.0, 150.0, 'Coop Ambassador', (SELECT id FROM companies WHERE name='Reliant'), 'Nighttime Boat Delivery', 'Grafton', 450.0, false, NULL, true, '314-803-4813', 'Went great. Trained Travis ', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-02-18', 'Travis Maurer', 2.0, 50.0, 'Training', NULL, NULL, NULL, NULL, NULL, NULL, true, NULL, 'Training', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-02-26', 'Training (Nipper)', 3.0, 75.0, 'R Stewart', (SELECT id FROM companies WHERE name='Kirby'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, NULL, true, '1-225-270-1132', 'Went Great. Trained Travis and Michael Chakur', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-02-26', 'Travis Maurer', 2.5, 62.5, 'Prosperity', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, NULL, true, '1-314-803-4832', 'Went Great.  Now ready for boat deliveries alone', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-02-27', 'Travis Maurer', 3.0, 75.0, 'Ardyce Randall', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Van Delivery', 'Arcto Terminal', 450.0, false, NULL, true, '1-314-803-4812', NULL, NULL, NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-03-05', 'Dad', 2.0, 0.0, 'Tom McCoin', (SELECT id FROM companies WHERE name='Southern Devall'), 'Crew Change', 'Grafton', 350.0, false, NULL, NULL, '901-734-0086', 'Laura Sent information to them per ach form but not set up.  Billing Contact per boat is Paula 901-734-0086', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-03-07', 'Travis Maurer', 7.0, 175.0, 'Coop Ambassador', (SELECT id FROM companies WHERE name='Reliant'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, NULL, true, '1-314-803-4813', 'ALL THE ISSUES.  Van battery was dead so Travis had to jump it.  Cooler leaked so we had to bring damaged goods to STL. ', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-03-09', 'Travis Maurer', 2.0, 150.0, 'REC', (SELECT id FROM companies WHERE name='Ingram'), 'Nighttime Boat Delivery', 'Grafton', 450.0, false, NULL, true, NULL, NULL, 'MK', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-03-09', 'Travis Maurer', 2.0, 150.0, 'Ardyce Randall', (SELECT id FROM companies WHERE name='Artco'), 'Nighttime Boat Delivery', 'Grafton', 450.0, false, NULL, true, NULL, NULL, 'MK', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-03-12', 'Travis Maurer', 2.25, 156.25, 'Co Op Mariner', (SELECT id FROM companies WHERE name='Reliant'), 'Nighttime Boat Delivery', 'Grafton', 450.0, false, NULL, true, NULL, NULL, 'MK', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-03-17', 'Nipper', 2.0, 150.0, 'Coop Ambassador', (SELECT id FROM companies WHERE name='Reliant'), 'nighttime Boat Delivery ', 'Grafton ', 450.0, false, NULL, true, '13148034813.0', '03:30:00', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-03-17', 'Dad Training ', NULL, NULL, 'New Dawn', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, NULL, NULL, '314-803-4830', 'No issues. Training went well would like to ride along one more time.', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-03-18', 'Travis Maurer', 3.0, 175.0, 'Show Me State ', (SELECT id FROM companies WHERE name='Marquette'), 'Nightime Boat Delivery', 'Grafton', 450.0, false, NULL, true, '270-217-4380', '04:30:00', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-03-18', 'Travis Maurer', 4.0, 100.0, 'Ardyce Randall', (SELECT id FROM companies WHERE name='Artco'), 'Van', 'Artco STL Terminal', 450.0, false, NULL, true, '314-803-4812', 'Filled up tank', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-03-22', 'John Critchfield ', 3.0, 75.0, 'Phillip Pfeffer', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery ', 'Sauget', 350.0, false, NULL, true, '270-933-0908', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-03-23', 'Brad Cumberledge', 3.5, 87.5, 'Coop Ambassador', (SELECT id FROM companies WHERE name='Reliant'), 'Daytime Van Delivery', 'STL Artco North Terminal', 450.0, false, NULL, true, '314-803-4813', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-03-29', 'Joe DeSherlia', 1.0, 0.0, 'Coop Mariner', (SELECT id FROM companies WHERE name='Reliant'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, NULL, NULL, '314-803-4815', 'Kevin Harmon started this delivery and never finished it. Joe finished it. ', 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-04-04', 'Travis Maurer', 2.0, 50.0, 'Brees', (SELECT id FROM companies WHERE name='Florida Marine'), 'Daytime Boat Delivery', 'Grafton', 350.0, true, NULL, true, '985-237-4598', ' ', 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-04-11', 'John Critchfield ', 2.0, 50.0, 'MV The Judge', (SELECT id FROM companies WHERE name='Southern Devall'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, NULL, true, '901-734-0180', 'Training Brad Did Great', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-04-11', 'Brad Cumberledge', 2.0, 50.0, 'Training', NULL, NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-04-14', 'Travis Maurer', 3.0, 175.0, 'Coop Ambassador', (SELECT id FROM companies WHERE name='Reliant'), 'Nightime Boat Delivery', 'Grafton', 450.0, false, NULL, true, '314-803-4813', '00:00:00', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-04-18', 'Travis Maurer', 2.0, 50.0, 'Lindsay Ann Erickson', (SELECT id FROM companies WHERE name='Marquette'), 'Van Delivery', 'PTL', 0.0, false, NULL, true, '270-559-6040', 'Fee waved. Marquette questioned this charge. Sinclairs delivered the groceries to us. We delivered them to PTL. PTL delivered them to the vessel. We waved our fee for "good will"', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-04-22', 'Travis Maurer', 3.0, 75.0, 'Coral Dawn', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, NULL, true, '314-803-4819', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-04-24', 'Travis Maurer', 2.0, 150.0, 'The Judge', (SELECT id FROM companies WHERE name='Southern Devall'), 'Dusk To Dawn boat Delivery', 'Grafton', 450.0, false, NULL, true, '901-734-0180', 'Started at 4:30am', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-04-24', 'Dad', NULL, 0.0, 'Darin Adrian', (SELECT id FROM companies WHERE name='Marquette'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, NULL, NULL, '270-217-3831', 'Freezer Items Sinclairs missed in first delivery to PTL. We brought ', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-04-26', 'Travis Maurer', 6.0, 150.0, 'Mr Lampton', (SELECT id FROM companies WHERE name='Magnolia'), 'Extended Van Delivery', 'Washington', 475.0, false, NULL, true, '601-415-7007', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-04-26', 'Travis Maurer', 2.0, 50.0, 'Coop Mariner', (SELECT id FROM companies WHERE name='Reliant'), 'Dusk To Dawn boat Delivery', 'Grafton', 450.0, false, NULL, true, '314-803-4815', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-04-26', 'Nipper', NULL, 100.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, NULL, 'Helped Travis and he wanted to give him night delivery fee', NULL, NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-04-29', 'Travis Maurer', 2.0, 50.0, 'Coop Ambassador', (SELECT id FROM companies WHERE name='Reliant'), 'Daytime Boat Delivery', 'Grafton ', 350.0, false, NULL, true, '314-803-4813', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-04-30', 'John Critchfield ', 2.0, 50.0, 'Ardyce Randall', (SELECT id FROM companies WHERE name='Artco'), 'Crew Change', 'Grafton ', 350.0, false, NULL, true, '314-803-4812', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-01', 'John Critchfield ', 2.0, 150.0, 'George King', (SELECT id FROM companies WHERE name='Marquette'), 'Dusk to Dawn Mechanic Transport', 'Grafton', 450.0, false, 0.0, true, '12702171419.0', '9;30 drop off', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-02', 'John Critchfield ', 2.0, 150.0, 'George King', (SELECT id FROM companies WHERE name='Marquette'), 'Dusk to Dawn Mechanic Pick Up', 'Grafton', 450.0, false, 0.0, true, NULL, '1am pickup', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-02', 'Nipper', 2.0, 150.0, 'Coop Mariner', (SELECT id FROM companies WHERE name='Reliant'), 'Dusk to Dawn Delivery ', 'Grafton', 450.0, false, 0.0, true, NULL, NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-02', 'Nipper', 2.0, 50.0, 'Philip Mpfeffer', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Boat Delivery ', 'Grafton', 350.0, false, 0.0, true, NULL, NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-04', 'John Critchfield ', 2.0, 50.0, 'Coop Vanguard', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Crew Change', 'Grafton', 350.0, false, 0.0, true, '314-803-4817', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-08', 'Travis Maurer', 2.0, 50.0, 'Coop Vanguard', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Crew Change 1/2 off ', 'Grafton', 150.0, false, 0.0, true, '314-803-4817', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-08', 'Travis Maurer', NULL, NULL, 'Coop Vanguard', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Grocery Delivery', 'Grafton', 350.0, false, 0.0, NULL, '314-803-4817', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-08', 'Travis Maurer', 3.0, 75.0, 'Prosperity', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Grocery Delivery', 'Grafton', 350.0, false, 0.0, true, '314-803-4832', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-11', 'Nipper DeSherlia', 3.0, 75.0, 'Ardyce Randall', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Grocery Delivery', 'Grafton', 350.0, false, 0.0, true, '314-803-4812', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-10', 'Nipper DeSherlia', 3.0, 175.0, 'Frankie Wiseman ', (SELECT id FROM companies WHERE name='Kirby'), 'Dusk to Dawn Grocery Delivery', 'Grafton', 450.0, false, 0.0, true, '1-225-432-0330', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-14', 'Keith Kasinger', 2.0, 50.0, 'Darin Adrian', (SELECT id FROM companies WHERE name='Marquette'), 'Daytime Grocery Delivery', 'Grafton', 350.0, false, 0.0, true, '270-217-3831', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-14', 'Travis Maurer', 3.0, 75.0, 'Coop Ambassador', (SELECT id FROM companies WHERE name='Reliant'), 'Daytime Van Delivery', 'Grafton', 350.0, false, 0.0, true, '314-803-4813', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-16', 'Nipper DeSherlia', 2.0, 150.0, 'Coop Mariner', (SELECT id FROM companies WHERE name='Reliant'), 'Nighttime Van Delivery', 'Grafton', 450.0, false, 0.0, true, '314-803-4815', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-17', 'Keith Kasinger', 2.0, 50.0, 'Coop Vanguard', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Van Delivery', 'Grafton', 350.0, false, 0.0, true, '1-314-803-4817', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-18', 'Nipper DeSherlia', 3.0, 75.0, 'Noble Parsonage', (SELECT id FROM companies WHERE name='ACBL'), 'Daytime Van Delivery', 'Grafton', 350.0, false, 0.0, true, '314-614-8237', 'Sinclairs sent us an invoice for this but MK confirmed with Dave that Sinclairs will bill for the groceries. 6/1/26', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-12', 'Keith Kasinger', 3.0, 75.0, 'Training', NULL, NULL, NULL, NULL, NULL, NULL, true, NULL, NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-12', 'Landon Crawford', NULL, NULL, 'Training', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-19', 'Rhylon DeSherlia', 4.0, 100.0, 'Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'East Carondalet', 225.0, true, 3065.17, true, '314-560-4533', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-21', 'Keith Kasinger', 2.5, 162.5, 'Ardyce Randall', (SELECT id FROM companies WHERE name='Artco'), 'Nighttime Boat Delivery', 'Grafton', 450.0, false, 0.0, true, '314-803-4812', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-22', 'Rhylon DeSherlia', 3.5, 87.5, 'Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'East Carondalet', 225.0, true, 2031.08, true, '314-560-4533', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-23', 'Travis Maurer', 4.0, 100.0, 'OA Franks', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'East Carondalet', 125.0, true, 1709.7, true, '270-933-0965', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-26', 'Jon Hughes', 2.0, 50.0, 'Coop Mariner', (SELECT id FROM companies WHERE name='Reliant'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, 0.0, true, '314-803-4815', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-27', 'Keith Kasinger', 4.5, 112.5, 'Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'East Carondalet', 225.0, true, 2363.83, true, '314-560-4533', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-28', 'Keith Kasinger', 2.25, 156.25, 'Prairie Dawn', (SELECT id FROM companies WHERE name='Artco'), 'Nighttime Boat Delivery', 'Grafton', 450.0, false, 0.0, true, '314-803-4831', '12-2AM', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-30', 'Keith Kasinger', 3.5, 87.5, 'Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'East Carondalet', 225.0, true, 1543.53, true, '314-560-4533', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-30', 'Keith Kasinger', 2.0, 50, 'Prairie Dawn', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, 0.0, true, '314-803-4831', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-05-31', 'Keith Kasinger', 3.0, 175, 'Paul Brotzge', (SELECT id FROM companies WHERE name='ACBL'), 'Nighttime Boat Delivery', 'Grafton', 450.0, false, 0.0, true, '812-786-9244', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-01', 'Keith Kasinger', 2.0, 150, 'D Dewaine Stephens', (SELECT id FROM companies WHERE name='Excel Marine'), 'Nightime Crew Change ', 'Grafton', 450.0, NULL, 0.0, true, '270-556-5388', 'Calling 6/1 with PO', 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-04', 'Keith Kasinger', 3.25, 81.25, 'Coop Mariner', (SELECT id FROM companies WHERE name='Reliant'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, 0.0, true, '314-803-4815', 'See comment. ', 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-04', 'Keith Kasinger', 3.5, 187.5, 'Coop Enterprises', (SELECT id FROM companies WHERE name='Artco'), 'Nighttime Van Delivery', 'Artco docks', 450.0, false, 0.0, true, '314-803-4814', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-05', 'Keith Kasinger', 3.25, 81.25, 'W Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'East Carondalet', 225.0, true, 3094.95, true, '314-560-4533', 'See comment.', 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-05', 'Keith Kasinger', 3.25, 181.25, 'Coop Ambassador', (SELECT id FROM companies WHERE name='Reliant'), 'Nighttime Boat Delivery', 'Grafton', 450.0, false, 0.0, true, '314-803-4813', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-08', 'Keith Kasinger', 5.0, 125, 'John Nugent', (SELECT id FROM companies WHERE name='ACBL'), 'Daytime Van Delivery= long distance', 'Clarksville', 475, false, 0.0, true, '812-786-2194', 'See comment', 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-08', 'Keith Kasinger', 3.5, 87.5, 'Mike Schmaeng', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'East Carondalet', 225.0, true, 2296.96, true, '504-415-2219', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-09', 'Coby Gibson (pay Jeremy)', 3.0, 75.0, 'W Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'East Carondalet', 225.0, true, 3335.37, true, '314-560-4533', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-10', 'Keith Kasinger', 4.5, 112.5, 'Kelly Rae Erickson', (SELECT id FROM companies WHERE name='Marquette'), 'Van Osage Dock', 'St. Louis', 450.0, false, 0.0, true, '270-217-1043', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-10', 'Keith Kasinger', 2.5, 62.5, 'Paul Brotzge', (SELECT id FROM companies WHERE name='ACBL'), 'Daytime boat delivery ', 'Grafton', 350.0, false, 0.0, true, '812-786-9244', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-12', 'Keith Kasinger', 3.0, 75, 'Andrew Koch', (SELECT id FROM companies WHERE name='ACBL'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, 0.0, true, '314-614-8229', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-12', 'Keith Kasinger', 3.25, 81.25, 'Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'East Carondalet', 225.0, true, 2300.39, true, '314-560-4533', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-12', 'Keith Kasinger', 0.0, 0.0, 'Jeff Boat (maybe)', (SELECT id FROM companies WHERE name='ACBL'), 'Daytime Boat Delivery', 'Grafton', NULL, false, 0.0, NULL, '812-786-9162', 'see comment', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-15', 'Keith Kasinger', 2.0, 50, 'Clearence Nixon', (SELECT id FROM companies WHERE name='Kirby'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, 0.0, true, '225-252-9159', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-16', 'Keith Kasinger', 3.25, 81.25, 'Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'East Charondelet', 225.0, true, 2949.04, true, '314-560-4533', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-18', 'Keith Kasinger', 2.0, 50, 'AA Birch', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Boat Delivery', 'Grafton', 350.0, true, 1622.78, true, '270-217-8460', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-18', 'Keith Kasinger', 2.5, 62.5, 'Frankie Wiseman ', (SELECT id FROM companies WHERE name='Kirby'), 'Daytime Van Delivery', 'East Charondelet', 450.0, false, 0.0, true, '225-432-0330', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-19', 'Keith Kasinger', 2.75, 68.75, 'Mike Schmaeng', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'PTL', 125.0, true, 1916.8, true, '504-415-2219', 'See comments', 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-19', 'Keith Kasinger', 2.5, 62.5, 'Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'East Charondelet ', 225.0, true, 2245.0, true, '314-560-4533', 'see comments', 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-19', 'Keith Kasinger', 2.0, 150, 'Ron Nokes', (SELECT id FROM companies WHERE name='Kirby'), 'Nighttime Boat Delivery ', 'Grafton', 450.0, false, 0.0, true, '346-339-4685', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-19', 'Keith Kasinger', 3.25, 181.25, 'Prosperity', (SELECT id FROM companies WHERE name='Artco'), 'Nightime Van Delivery', 'Artco Terminal', 450.0, false, 0.0, true, '314-803-4832', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-21', 'Nipper DeSherlia', 2.0, 50, 'Michael Draughn', (SELECT id FROM companies WHERE name='ACBL'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, 0.0, true, '812-786-9235', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-23', 'Travis Maurer', 2.5, 62.5, 'Tony Espinoza', (SELECT id FROM companies WHERE name='ACBL'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, 0.0, true, '314-614-8230', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-23', 'Travis Maurer', 3.0, 75.0, 'Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'East Charondelet', 225.0, true, 2087.63, true, '225-432-0330', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-23', 'Travis Maurer', 3.0, 75.0, 'Coop Vanguard', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, 0.0, true, '314-803-4817', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-23', 'Travis Maurer', 2.0, 75.0, 'Coop Mariner', (SELECT id FROM companies WHERE name='Reliant'), 'Dusk to Dawn Boat Delivery', 'Grafton', 450.0, false, 0.0, true, '314-803-4815', '00:30:00', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-23', 'Travis Maurer', 2.0, 50.0, 'David Evans', (SELECT id FROM companies WHERE name='ACBL'), 'Daytime Van Delivery', 'Campsville', 350.0, false, 0.0, true, '812-786-9251', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-24', 'Tommy Tucker', 4.5, 112.5, 'Coral Dawn', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Van Delivery', 'Artco STL Terminal', 450.0, false, 0.0, true, '314-803-4819', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-24', 'Travis Maurer', 3.5, 137.5, 'Coop Ambassador', (SELECT id FROM companies WHERE name='Reliant'), 'Dusk to Dawn Boat Delivery', 'Grafton', 450.0, false, 0.0, true, '314-803-4813', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-24', 'Tommy Tucker', 3.5, 137.5, 'Training', NULL, NULL, NULL, NULL, false, 0.0, true, NULL, NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-23', 'Tommy Tucker', 10.0, 250.0, 'Training', NULL, NULL, NULL, NULL, false, 0.0, true, NULL, NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-25', 'Tommy Tucker', 4.0, 100.0, 'Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'East Charondelet', 225.0, true, 1855.94, true, '225-432-0330', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-26', 'Keith Kasinger', 3.75, 93.75, 'Gregory David', (SELECT id FROM companies WHERE name='Reliant'), 'Daytime Van Delivery', 'Ingram dock', 350.0, false, 0.0, true, '270-564-7334', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-26', 'Keith Kasinger', 3.5, 87.5, 'Mike Schmeng', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'Ingram dock', 225.0, true, 2132.07, true, '504-415-2219', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-30', 'Keith Kasinger', 2.75, 168.75, 'Coop Vanguard', (SELECT id FROM companies WHERE name='Artco'), 'Nighttime Boat Delivery', 'Grafton', 450.0, false, 0.0, true, '314-803-4817', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-06-30', 'Keith Kasinger', 3.75, 93.75, 'Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'Ingram dock', 225.0, true, 4347.13, true, '225-432-0330', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-03', 'Coby Gibson (pay Jeremy)', 2.0, 50, 'W Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'Ingram dock', 225.0, true, 1494.18, true, '573-291-1530', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-03', 'Coby Gibson (pay Jeremy)', 2.0, 50, 'Mike Schmeng', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'Ingram dock', 225.0, true, 1585.66, true, '504-415-2219', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-03', 'Coby Gibson (pay Jeremy)', 2.0, 50, 'Andrew F Koch', (SELECT id FROM companies WHERE name='ACBL'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, 0.0, true, '314-614-8229', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-03', 'Coby Gibson (pay Jeremy)', 2.0, 50, 'Prosperity', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, 0.0, true, '314-803-4832', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-06', 'Keith Kasinger', 3.75, 193.75, 'Philip Pfeffer', (SELECT id FROM companies WHERE name='Ingram'), 'Nightime Van Delivery', 'Ingram dock', 325, true, 3986.32, true, '270-933-0908', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-07', 'Tommy Tucker', 3.0, 75, 'Rick Hay', (SELECT id FROM companies WHERE name='Excel Marine'), 'Daytime Van Delivery', 'Hardin Launching Ramp', 350.0, false, 0.0, true, 'Personal 601-529-4507, boat 270-792-8352', 'Extra large delivery', 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-08', 'Keith Kasinger', 2.0, 50, 'Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'Ingram dock', 225.0, true, 3333.88, true, '314-560-4533 (greg)', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-08', 'Tommy Tucker', 3.5, 87.5, 'Coop Mariner', (SELECT id FROM companies WHERE name='Reliant'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, 0.0, true, '314-803-4815', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-09', 'Keith Kasinger', 2.0, 150, 'Prairie Dawn', (SELECT id FROM companies WHERE name='Artco'), 'Nighttime Boat Delivery', 'Grafton', 450.0, false, 0.0, true, '314-803-4831', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-10', 'Keith Kasinger', 4.25, 106.25, 'W Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'Ingram Docks', 225.0, true, 1539.03, true, '270-933-0908', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-10', 'Keith Kasinger', 5.5, 137.5, 'John Nugent', (SELECT id FROM companies WHERE name='ACBL'), 'Nightime Long Distance Delivery', 'Lock 22', 522.5, false, 0.0, true, '812-786-2194', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-11', 'Keith Kasinger', 4.0, 100, 'Mike Schmeng', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'Ingram Dock', 225.0, true, 1324.62, true, '314-560-4533 (greg)', NULL, 'Jen', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-14', 'Tommy Tucker', 3.5, 87.5, 'Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'Ingram Dock', 225.0, true, 3021.99, true, '314-560-4533 (greg)', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-14', 'Keith Kasinger', 3.0, 75.0, 'Coop Ambassador', (SELECT id FROM companies WHERE name='Reliant'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, 0.0, true, '314-803-4813', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-17', 'Tommy Tucker', 3.25, 81.25, 'Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'Ingram Dock', 225.0, true, 2702.57, true, '314-560-4533 (greg)', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-16', 'Tommy Tucker', 3.0, 75, 'Crimson Glory', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Van Delivery', 'Artco', 450.0, false, 0.0, true, '314-803-4822', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-19', 'Keith Kasinger', 3.0, 75.0, 'Mike Schmeng', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'Ingram Dock', 225.0, true, 2682.84, true, '314-560-4533 (greg)', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-20', 'Tommy Tucker', 3.0, 75.0, 'Coop Mariner', (SELECT id FROM companies WHERE name='Reliant'), 'Daytime Boat Delivery', 'Grafton', 350.0, false, 0.0, true, '314-803-4815', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-21', 'Keith Kasinger', 4.0, 100.0, 'Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery', 'Ingram Dock', 225.0, true, 2278.38, true, '314-560-4533 (greg)', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-22', 'Tommy Tucker', 2.0, 50.0, 'Nick G Buford', (SELECT id FROM companies WHERE name='Tennessee Valley Towing'), 'Daytime Crew Change', 'Grafton', 350.0, false, 0.0, true, '270-331-8645', 'Billing 270-554-0154 
Gail OConnell
270-898-7392', 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-23', 'Tommy Tucker', 3.0, 75.0, 'Scott Noble', (SELECT id FROM companies WHERE name='Ingram'), 'Daytime Van Delivery ', 'Ingram', 225.0, true, 1493.69, true, '314-560-4533 (greg', NULL, 'Laura', NULL, NULL);
INSERT INTO deliveries (delivery_date, delivery_driver, hours_worked, amount_paid_driver, vessel_name, company_id, service_type, location_delivered, delivery_fee, bill_for_groceries, sinclairs_grocery_total, updated_quickbooks, phone_number_used, issues_comments, gts_correspondent, invoice_sent, incentive) VALUES
('2026-07-24', 'Travis Maurer', 3.0, 50.0, 'Crimson Glory', (SELECT id FROM companies WHERE name='Artco'), 'Daytime Boat Delivery ', 'Grafton', 350.0, false, 0.0, true, '314-803-4822', NULL, NULL, NULL, NULL);